config/routes.rb
Rails.application.routes.draw do

	root to: 'trackme#home'
  devise_for :users
  
  resources :runs do
  	resources :locations
  end
	

  get 'trackme/live'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :run
end

app/models/run.rb
class Run < ApplicationRecord
	belongs_to :user
	has_many :locations, dependent: :destroy

	def km
		if self.distance
			return self.distance / 1000
		else
			return 0
		end
	end

	def dur
		if self.duration
			return Time.at(self.duration).utc.strftime("%H:%M:%S")
		else
			return
		end
	end

	def kmh
		if self.duration && self.distance
			return (self.distance/1000) / (self.duration/3600)
		else
			return 0
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :runs, dependent: :destroy

  def username
  	return self.email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :set_run

  # GET /locations
  # GET /locations.json
  def index
    @locations = @run.locations
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to run_location_path(@run,@location), notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to run_location_path(@run,@location), notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to run_locations_url(@run), notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    def set_run
      @run = Run.find(params[:run_id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:logged_at, :latitude, :longitude, :run_id)
    end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :set_run, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /runs
  # GET /runs.json
  def index
    @runs = current_user.runs.order('started_at DESC')
  end

  # GET /runs/1
  # GET /runs/1.json
  def show
  end

  # GET /runs/new
  def new
    @run = Run.new
  end

  # GET /runs/1/edit
  def edit
  end

  # POST /runs
  # POST /runs.json
  def create
    @run = Run.new(run_params)
    @run.user = current_user
    respond_to do |format|
      if @run.save
        format.html { redirect_to root_path, notice: 'Run was successfully created.' }
        format.json { render :show, status: :created, location: @run }
      else
        format.html { redirect_to root_path }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /runs/1
  # PATCH/PUT /runs/1.json
  def update
    respond_to do |format|
      if @run.update(run_params)
        format.html { redirect_to root_path, notice: 'Run was successfully updated.' }
        format.json { render :show, status: :ok, location: @run }
      else
        format.html { redirect_to root_path }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /runs/1
  # DELETE /runs/1.json
  def destroy
    @run.destroy
    respond_to do |format|
      format.html { redirect_to runs_url, notice: 'Run was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_run
      @run = Run.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def run_params
      params.require(:run).permit(:title, :distance, :duration, :started_at, :ended_at, :note, :finished, :paused)
    end
end

app/controllers/trackme_controller.rb
class TrackmeController < ApplicationController
  def live
  	# ActionCable.server.broadcast('notifications_channel', 'You have visited the welcome page.')
  end

  def home
  	if current_user
	  	@run = current_user.runs.where(finished: false).order('started_at').last
	  	if !@run
	  		@run = Run.new
	  	end
	  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/helpers/trackme_helper.rb
module TrackmeHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark ">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if current_user %> 
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#"><%= current_user.username %> <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Profile</a>
        </li>
        <% if current_user.admin %> 
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Admin
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Users</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>     
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-sm btn-outline-primary" %>
    <% else %>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "btn btn-sm btn-light" %>
        </li>
        <li class="nav-item">
          <%= link_to  "Sign Up", new_user_registration_path, class: "btn btn-sm btn-primary" %>
        </li>
      </ul>  
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trackme</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <main role="main" class="container">
      <%= render 'layouts/alerts' %>
      <%= yield %>
    </main> 
  </body>
</html>

app/views/locations/_form.html.erb
<%= simple_form_for([@run, location]) do |f| %>
  <%= f.error_notification %>
  <%= f.input :run_id, label: @run.title , :as => :hidden, input_html: {value: @run.id} %>
  <%= f.input :logged_at %>
  <%= f.input :latitude %>
  <%= f.input :longitude %>
  <%= f.submit %>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', run_location_path(@run,@location) %> |
<%= link_to 'Back', run_locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<div id="<%= @locations.exists? ? 'trackmap2' : ''%>"></div>

<%= content_tag "div", 
  @locations.exists? ? 
  {id: 'trackmap', data: {locations: @locations.select('latitude','longitude')}} : 
  '' do %>
<% end %>

<br>
<div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Logged at</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Run</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.logged_at %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= location.run_id %></td>
        <td><%= link_to 'Show', run_location_path(@run,location) %></td>
        <td><%= link_to 'Edit', edit_run_location_path(@run,location) %></td>
        <td><%= link_to 'Destroy', run_location_path(@run, location), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Location', new_run_location_path %> |
<%= link_to 'Show Run', @run %>

<%= javascript_tag do %>
  <% if @locations.exists? %>
    var map = L.map('trackmap');
    var latlngs = JSON.parse(document.getElementById('trackmap').dataset.locations).map(c => [c.latitude, c.longitude])
    iniRunMap(map, latlngs);
  <% end %>
<% end %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', run_locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Logged at:</strong>
  <%= @location.logged_at %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<p>
  <strong>Run:</strong>
  <%= @location.run_id %>
</p>

<%= link_to 'Edit', edit_run_location_path(@run,@location) %> |
<%= link_to 'Back', run_locations_path %>

app/views/runs/_form.html.erb
<%= simple_form_for(run) do |f| %>
  <%= f.error_notification %>
  <%= f.input :title %>
  <%= f.input :distance %>
  <%= f.input :duration %>
  <%= f.input :started_at %>
  <%= f.input :ended_at %>
  <%= f.input :finished %>
  <%= f.input :paused %>
  <%= f.input :note %>
  <%= f.submit %>
<% end %>

app/views/runs/_mapCard.html.erb
<div class="card border-primary mb-3" >
  <div class="card-header bg-primary border-primary text-white ">
    <div >
      <i class="fas fa-running fa-3x mx-2" style="float:left;"></i>
      <div>
        <h4><%= run.title %></h4>
        <%= run.started_at ? run.started_at.strftime("%A, %e %B %Y - %l:%M %P") : "No Starting Time" %>
      </div>
    </div>
  </div>
  <div class="card-body text-primary", style="padding-left: 0; padding-right: 0; padding-top: 0; padding-bottom: 0;">
    <% if run.locations.exists? %>
      <%= content_tag "div", 
        class: "listmap", id: 'map'+run.id.to_s+'''', data: {locations: run.locations.select('latitude','longitude')} do %>
      <% end %>

      <%= javascript_tag do %>
        var map<%= run.id %> = L.map('map<%= run.id %>');
        var latlngs = JSON.parse(document.getElementById('map<%= run.id %>').dataset.locations).map(c => [c.latitude, c.longitude])
        iniRunMap(map<%= run.id %>, latlngs);
        delete latlngs;
      <% end %>

    <% end %>
  </div>
  <div class="card-footer bg-transparent border-primary", style="padding-bottom: 0;">
    <table class="table table-borderless text-center ">
      <thead></thead>
      <tbody>        
        <tr>
          <td>
            <h5><%= number_with_precision(run.km, precision: 2, strip_insignificant_zeros: true) %></h5>
            <p>KM</p>
          </td>
          <td>
            <h5><%= run.dur %></h5>
            <p>Duration</p>
          </td>
          <td>
            <h5><%= number_with_precision(run.kmh, precision: 2, strip_insignificant_zeros: true) %></h5>
            <p>Km/h</p>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/runs/edit.html.erb
<h1>Editing Run</h1>

<%= render 'form', run: @run %>

<%= link_to 'Show', @run %> |
<%= link_to 'Back', runs_path %>

app/views/runs/index.html.erb
<%= link_to root_path do %>
    <i class="fas fa-arrow-circle-left fa-3x mx-2 text-secondary"></i>
<% end %>

<% @runs.each do |run| %>
  <%= link_to run, {style: "text-decoration:none" } do %>
    <%= render 'mapCard', run: run %>
  <% end %>
<% end %>

app/views/runs/new.html.erb
<h1>New Run</h1>

<%= render 'form', run: @run %>

<%= link_to 'Back', runs_path %>

app/views/runs/show.html.erb
<%= link_to runs_path do %>
    <i class="fas fa-arrow-circle-left fa-3x mx-2 text-secondary"></i>
<% end %>

<%= render 'mapCard', run: @run %>

<div class="card border-primary mb-3" >
  <div class="card-header border-primary text-primary ">
    <div >      
      <h4>More Info</h4>
    </div>
  </div>
  <div class="card-body">
    <h5>Activity Hours:</h5>
    <p><%= @run.started_at ? @run.started_at.strftime("%l:%M %P") : "No Starting Time"%> to <%= @run.ended_at ? @run.ended_at.strftime("%l:%M %P") : "No Finished Time" %> </p>
    <h5>Notes:</h5>
    <p><%= (@run.started_at && @run.ended_at) ? distance_of_time_in_words(@run.started_at, @run.ended_at) : ""%></p>
    <p><%= @run.note %></p>
  </div>
  <div class="card-footer bg-transparent border-primary">
    <table class="table table-borderless text-center ">
      <thead></thead>
      <tbody>        
        <tr>
          <td>
            <%= link_to  "Edit", edit_run_path(@run), class: "btn btn-lg btn-warning " %>
          </td>
          <td>
            <%= link_to  "Delete", @run, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-lg btn-danger " %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/trackme/home.html.erb
<% if current_user %> 

	<% if @run.new_record? %>
		<div>
			<%= simple_form_for(@run) do |f| %>
				<%= f.input :title, :as => :hidden %>
				<%= f.input :started_at, :as => :hidden%>
				<%= link_to  "Start Activity", "", id: "start_btn", class: "btn btn-lg btn-warning btn-block", onclick: "start_btn(this);" %>
			<% end %>
			<br>
			<%= link_to  "History of Activities", runs_path, id: "history_btn", class: "btn btn-lg btn-primary btn-block" %>
			<br>
			<div id='trackmap'></div>
	
			<%= javascript_tag do %>
				var map = L.map('trackmap');
				var marker = L.circleMarker([0, 0]).addTo(map);
				liveTrack(map);

				start_btn = function(form){
					run_title.value = "Test Crear"
			  	run_started_at.value = Date(Date.now());
			  	new_run.submit();
				}
			<% end %>
		</div>		
	<% else %>
		<div>
			<h4> <%= @run.title %> - Activity in progess </h4>
			<%= simple_form_for(@run) do |f| %>
				<%= f.input :finished, :as => :hidden %>
				<%= f.input :ended_at, :as => :hidden%>
				<%= f.submit "Finish Activity", class: "btn btn-lg btn-danger btn-block", onclick: "finish_btn(this);"%>
			<% end %>
			<br>
			<div id='trackmap'></div>

			<div>
				<p>DB logs: 
				<span id="db_log">0</span>
				</p>
			</div>


			<%= javascript_tag do %>
				var map = L.map('trackmap');
				var marker = L.circleMarker([0, 0]).addTo(map);
				var run_id = <%= @run.id %>;
				runTrack(map);
				var gps_sens = <%= ENV['GPS_SENS'].to_i %>;

				finish_btn = function(form){
					run_finished.value = true
			  	run_ended_at.value = Date(Date.now());
			  	new_run.submit();
				}
			<% end %>
		</div>
	<% end %>


	
<% else %>
	<h3> Please Sign In</h3>
<% end %>

app/views/trackme/live.html.erb
<h1>Live Tracking</h1>

<div>
	<span id="latlng">0 0</span>
</div>

<div>
	<p>DB logs: 
	<span id="db_log">0</span>
	</p>
</div>

<br>

<div>
  <input type="checkbox" onclick="liveTrack()" id="liveTrack">
</div>


<br>

<div id='trackmap'></div>

<%= javascript_tag do %>
	var map = L.map('trackmap');
	var marker = L.circleMarker([0, 0]).addTo(map);
<% end %>